#!/bin/bash
# File: .devcontainer/manage/lib/version-utils.sh
# Purpose: Shared version checking utilities for dev-* commands
#
# Two version systems:
#   - Container version (version.txt): manual bump, requires docker rebuild via dev-update
#   - Scripts version (scripts-version.txt): auto-generated by CI, no rebuild via dev-sync
#
# Usage:
#   source "$(dirname "${BASH_SOURCE[0]}")/lib/version-utils.sh"
#   show_version_info        # Shows version and update availability
#   show_version_info short  # Shows compact one-line version

# Get the .devcontainer directory (parent of manage/lib)
_get_devcontainer_dir() {
    local script_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
    # Go up from lib/ to manage/ to .devcontainer/
    echo "$(cd "$script_dir/../.." && pwd)"
}

# ─── Container version ──────────────────────────────────────────────────────

# Read container version info from .version file or version.txt
# Sets: TOOLBOX_VERSION, TOOLBOX_REPO
_load_version_info() {
    local devcontainer_dir="$(_get_devcontainer_dir)"
    local version_file="$devcontainer_dir/.version"
    local workspace_root="$devcontainer_dir/.."
    local version_txt="$workspace_root/version.txt"

    TOOLBOX_VERSION="unknown"
    TOOLBOX_REPO=""

    # First try .devcontainer/.version (created by dev-update for installed users)
    if [ -f "$version_file" ]; then
        TOOLBOX_VERSION=$(grep "^VERSION=" "$version_file" 2>/dev/null | cut -d= -f2)
        TOOLBOX_REPO=$(grep "^REPO=" "$version_file" 2>/dev/null | cut -d= -f2)
    # Image mode: version.txt is inside $DCT_HOME (not in parent dir)
    elif [ -n "$DCT_HOME" ] && [ -f "$DCT_HOME/version.txt" ]; then
        TOOLBOX_VERSION=$(cat "$DCT_HOME/version.txt" 2>/dev/null | tr -d '[:space:]')
        TOOLBOX_REPO="terchris/devcontainer-toolbox"
    # Copy mode: version.txt in workspace root (parent of .devcontainer/)
    elif [ -f "$version_txt" ]; then
        TOOLBOX_VERSION=$(cat "$version_txt" 2>/dev/null | tr -d '[:space:]')
    fi
}

# Check for available container updates (quick, with timeout)
# Sets: TOOLBOX_REMOTE_VERSION (empty if check failed or same version)
_check_for_updates() {
    TOOLBOX_REMOTE_VERSION=""

    if [ -n "$TOOLBOX_REPO" ]; then
        local remote=$(curl -fsSL --connect-timeout 2 "https://raw.githubusercontent.com/$TOOLBOX_REPO/main/version.txt" 2>/dev/null || echo "")
        if [ -n "$remote" ] && [ "$remote" != "$TOOLBOX_VERSION" ]; then
            TOOLBOX_REMOTE_VERSION="$remote"
        fi
    fi
}

# ─── Scripts version ─────────────────────────────────────────────────────────

# Read scripts version from scripts-version.txt
# Sets: SCRIPTS_VERSION
_load_scripts_version_info() {
    SCRIPTS_VERSION="unknown"

    # Image mode: scripts-version.txt is inside $DCT_HOME
    if [ -n "$DCT_HOME" ] && [ -f "$DCT_HOME/scripts-version.txt" ]; then
        SCRIPTS_VERSION=$(grep "^SCRIPTS_VERSION=" "$DCT_HOME/scripts-version.txt" 2>/dev/null | cut -d= -f2)
    else
        # Copy mode: scripts-version.txt in workspace root
        local devcontainer_dir="$(_get_devcontainer_dir)"
        local workspace_root="$devcontainer_dir/.."
        if [ -f "$workspace_root/scripts-version.txt" ]; then
            SCRIPTS_VERSION=$(grep "^SCRIPTS_VERSION=" "$workspace_root/scripts-version.txt" 2>/dev/null | cut -d= -f2)
        fi
    fi
}

# Check for available scripts updates (quick, with timeout)
# Requires: _load_version_info() called first (sets TOOLBOX_REPO)
# Sets: SCRIPTS_REMOTE_VERSION (empty if check failed or same version)
_check_for_scripts_updates() {
    SCRIPTS_REMOTE_VERSION=""

    if [ -n "$TOOLBOX_REPO" ]; then
        local remote_content=$(curl -fsSL --connect-timeout 2 "https://raw.githubusercontent.com/$TOOLBOX_REPO/main/scripts-version.txt" 2>/dev/null || echo "")
        local remote_ver=$(echo "$remote_content" | grep "^SCRIPTS_VERSION=" 2>/dev/null | cut -d= -f2)
        if [ -n "$remote_ver" ] && [ "$remote_ver" != "$SCRIPTS_VERSION" ]; then
            SCRIPTS_REMOTE_VERSION="$remote_ver"
        fi
    fi
}

# ─── Display ─────────────────────────────────────────────────────────────────

# Display version info with optional update notification
# Usage: show_version_info [short]
#   short: Single line format for welcome message
#   (default): Full format for dev-help
show_version_info() {
    local format="${1:-full}"

    _load_version_info
    _load_scripts_version_info
    _check_for_updates
    _check_for_scripts_updates

    if [ "$format" = "short" ]; then
        # Compact format for welcome message
        if [ -n "$TOOLBOX_REMOTE_VERSION" ]; then
            echo "  DevContainer Toolbox v$TOOLBOX_VERSION - Container update available: v$TOOLBOX_REMOTE_VERSION (run 'dev-update')"
        elif [ -n "$SCRIPTS_REMOTE_VERSION" ]; then
            echo "  DevContainer Toolbox v$TOOLBOX_VERSION - Scripts update available (run 'dev-sync')"
        else
            echo "  DevContainer Toolbox v$TOOLBOX_VERSION - Type 'dev-help' for commands"
        fi
    else
        # Full format for dev-help
        echo "DevContainer Toolbox v$TOOLBOX_VERSION (scripts: $SCRIPTS_VERSION)"
        if [ -n "$TOOLBOX_REMOTE_VERSION" ]; then
            echo "  ⬆️  Container update available: v$TOOLBOX_REMOTE_VERSION (run 'dev-update')"
        fi
        if [ -n "$SCRIPTS_REMOTE_VERSION" ]; then
            echo "  ⬆️  Scripts update available: $SCRIPTS_REMOTE_VERSION (run 'dev-sync')"
        fi
    fi
}
